//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedDeadOnlineCustomRoom {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedDeadOnlineCustomRoom.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;CDataFileMgr__ContentsOfDataFileXml&gt;
        /// &lt;disabledFiles /&gt;
        /// &lt;includedXmlFiles itemType=&quot;CDataFileMgr__DataFileArray&quot; /&gt;
        /// &lt;includedDataFiles /&gt;
        /// &lt;dataFiles itemType=&quot;CDataFileMgr__DataFile&quot;&gt;
        ///  &lt;Item&gt;
        ///   &lt;filename&gt;platform:/data/cdimages/scaleform_platform_pc.rpf&lt;/filename&gt;
        ///   &lt;fileType&gt;RPF_FILE&lt;/fileType&gt;
        ///  &lt;/Item&gt;
        ///  &lt;Item&gt;
        ///   &lt;filename&gt;platform:/data/ui/value_conversion.rpf&lt;/filename&gt;
        ///   &lt;fileType&gt;RPF_FILE&lt;/fileType&gt;
        ///  &lt;/Item&gt;
        ///  &lt;Item&gt;
        ///   &lt;filename&gt;platfor [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string startup {
            get {
                return ResourceManager.GetString("startup", resourceCulture);
            }
        }
    }
}
